# Generated by Django 4.0.5 on 2022-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('roll_number', models.IntegerField(help_text='Enter a 6 digit roll number')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
